use_frameworks!

target 'SnoTelAPI_Example' do
  pod 'SnoTelAPI', :path => '../'

  target 'SnoTelAPI_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
